### ISSUE TITLE
Neovis.js html code

### ISSUE THREAD

**Issue by myrulezzz** [gapitio/gapit-htmlgraphics-panel#132]
Hi i have a neo4j graph using neovis.js library in an html file. And i was looking to visualize this graph in grafana. Is possible to do this with html graphics plugin?

**Comment by ZuperZee** [comment]
The best way would be to use a bundler like https://github.com/gapitio/htmlgraphics-html-bundler-template, because imports inside the HTML currently aren't possible https://github.com/gapitio/gapit-htmlgraphics-panel/issues/65.
I briefly tested it and it seems like the code uses `document.getElementById()` to get a container instead of an element, which means some code changes have to be made to the neovis.js code.

The issue https://github.com/gapitio/gapit-htmlgraphics-panel/issues/41 might also help you with how to import external dependencies.

**Comment by ZuperZee** [comment]
Just checking in as there's been some time since the last message. Did you figure something out, or are you still looking for a solution?

**Comment by ZuperZee** [comment]
Closing as this has been open for a while. Create a new issue if this hasn't been resolved.
